"""generated migration

Revision ID: 26a2772ec6e8
Revises:
Create Date: 2025-11-02 14:45:07.261651

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "26a2772ec6e8"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "uploadmetadata",
        sa.Column("pk", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("upload_id", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("content_type", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.PrimaryKeyConstraint("pk"),
    )
    op.create_index(
        op.f("ix_uploadmetadata_upload_id"), "uploadmetadata", ["upload_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_uploadmetadata_upload_id"), table_name="uploadmetadata")
    op.drop_table("uploadmetadata")
    # ### end Alembic commands ###
