"""add tag and uploadtag tables

Revision ID: 8b52c1b9f73b
Revises: 26a2772ec6e8
Create Date: 2026-04-04 14:27:21.913707

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8b52c1b9f73b"
down_revision: str | Sequence[str] | None = "26a2772ec6e8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tag",
        sa.Column("pk", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.PrimaryKeyConstraint("pk"),
    )
    op.create_index(op.f("ix_tag_name"), "tag", ["name"], unique=True)
    op.create_table(
        "uploadtag",
        sa.Column("upload_pk", sa.Uuid(), nullable=False),
        sa.Column("tag_pk", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["tag_pk"], ["tag.pk"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["upload_pk"], ["uploadmetadata.pk"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("upload_pk", "tag_pk"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("uploadtag")
    op.drop_index(op.f("ix_tag_name"), table_name="tag")
    op.drop_table("tag")
    # ### end Alembic commands ###
